name: catat_kelas
description: "Aplikasi administrasi keuangan sekolah modern."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  pdf: ^3.11.1
  printing: ^5.13.4
  firebase_core: ^3.6.0
  cloud_firestore: ^5.5.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
